Repository cms-sw/cms-git-tools, pull requests merged in 2022-10, with the labels that each got.

#123 Minor updates
  git-cms-cherry-pick-pr
  git-cms-fetch-pr
  git-cms-show-pr
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#122 Update git-cms-checkdeps
  git-cms-checkdeps
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#124 Bug fix: only keep valid dependencies
  git-cms-checkdeps
Labels: orp-pending, pending-signatures, tests-approved, externals-pending
